name: dddd
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        T: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo $T >> secrets.txt
        cat secrets.txt
